### PR TITLE
MCE Community version install

### PR DESCRIPTION
**Pull request by eemurphy**
Signed-off-by: Erin Murphy erinmurp@redhat.com

issue: https://github.com/stolostron/backlog/issues/21971

### CODE REVIEW

**Comment by JakobGray** [comment]
@eemurphy I'm a little confused by some of the changes. Was the search content something pulled in from one of Cameron's branches? Functionally would this differ from something like this? https://github.com/stolostron/multiclusterhub-operator/compare/main...JakobGray:multiclusterhub-operator:comm-check?expand=1

**Comment by eemurphy** [comment]
@JakobGray It works the same! Only thing is your code has:
`if err != nil {
		community = true // community by default
}`

That would cause even in acm mode to be community, because if it's acm, community returns false but no error still.

The search changes were purely because tests in mch-controller were failing. It would try to get the AppSubs in community mode and would look for search-prod-sub, which doesn't exist and would fail. It would need the search v2 deployment instead.

**Comment by JakobGray** [comment]
I'll approve and we can refactor as necessary when pulling out the search-v2 content

**Pull request merged**
