### PR TITLE
Upgrade client-go to v0.27.2 and controller-runtime to v0.15.0

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>

### CODE REVIEW

**Comment by yanmxa** [comment]
Blocked by https://github.com/stolostron/backplane-operator/pull/493

```
# github.com/stolostron/backplane-operator/api/v1
vendor/github.com/stolostron/backplane-operator/api/v1/multiclusterengine_webhook.go:102:27: cannot use &MultiClusterEngine{} (value of type *MultiClusterEngine) as admission.Validator value in variable declaration: *MultiClusterEngine does not implement admission.Validator (wrong type for method ValidateCreate)
                have ValidateCreate() error
                want ValidateCreate() (admission.Warnings, error)
make: *** [Makefile:93: vet] Error 1
```

**Comment by yanmxa** [comment]
ref: https://github.com/stolostron/multicluster-global-hub/pull/600

**Comment by dislbenn** [comment]
/override ci/prow/sonar-pre-submit "SonarCloud Code Analysis"

Overriding to unblock the PR. We will aim to increase the code-coverage within a separate PR.

**Pull request merged**
