### PR TITLE
search-v2

### PR DESCRIPTION
**Pull request by cameronmwall**
Signed-off-by: Cameron Wall <cwall@redhat.com>

### CODE REVIEW

**Comment by cameronmwall** [comment]
@JakobGray to answer your question on the other PR, apparently we are still missing one image reference in the upstream pipeline. I contacted @gurnben and opened an issue so hopefully that should be squared away shortly

**Comment by cameronmwall** [comment]
> @JakobGray to answer your question on the other PR, apparently we are still missing one image reference in the upstream pipeline. I contacted @gurnben and opened an issue so hopefully that should be squared away shortly

This has been remedied and all image references are up-to-date

**Review by JakobGray — CHANGES_REQUESTED** [review]
Some things I found while testing: 
- search-v2 isn't tracked anywhere in the status. mch immediately displays `running` when enabling search-v2
- mch doesn't react to the `search-v2-operator-controller-manager` deployment being deleted. If I delete it it stays gone. If I then delete `multiclusterhub-repo` both deployments will come back.
- the search-v2 deployment is missing installer labels. adding those should resolve the point above

**Comment by cameronmwall** [comment]
> Some things I found while testing:
> 
>     * search-v2 isn't tracked anywhere in the status. mch immediately displays `running` when enabling search-v2
> 
>     * mch doesn't react to the `search-v2-operator-controller-manager` deployment being deleted. If I delete it it stays gone. If I then delete `multiclusterhub-repo` both deployments will come back.
> 
>     * the search-v2 deployment is missing installer labels. adding those should resolve the point above

Both of these should be cleared up. There was in quotation marks left in for the status that were affecting it. And installer labels have been added which did indeed fix the deletion problem

**Pull request merged**
