### PR TITLE
bundle automation - enable search v2

### PR DESCRIPTION
**Pull request by eemurphy**
Signed-off-by: Erin Murphy <erinmurp@redhat.com>

issue: https://github.com/stolostron/backlog/issues/26944

### CODE REVIEW

**Comment by cameronmwall** [comment]
@xrajesh Do you mind checking these search changes to make sure we are good to go with automating pulling from the bundle

**Review by xrajesh — APPROVED** [review]

**Comment by JakobGray** [comment]
It seems like this commit is basically doing a revert of [this commit](https://github.com/stolostron/multiclusterhub-operator/pull/860/files). @cameronmwall Does that seem right? If all that was needed was uncommenting it in the config why was it commented out in the first place when you migrated appsub?

**Comment by cameronmwall** [comment]
@JakobGray I think it was because we were waiting for search's signoff and Xavier was out of office or something? We were trying to move forward without having to wait on them I believe

**Pull request merged**
