### PR TITLE
MCH Console Fix

### PR DESCRIPTION
**Pull request by eemurphy**
Signed-off-by: Erin Murphy <erinmurp@redhat.com>

### CODE REVIEW

**Comment by JakobGray** [comment]
@eemurphy Can you share the output when you run the unit tests locally?

**Comment by JakobGray** [comment]
@eemurphy This branch has fallen several commits behind main. After pulling and rebasing I get an error while running tests due to this test recently introduced https://github.com/JakobGray/multiclusterhub-operator/blob/reb/pkg/utils/utils_test.go#L235

**Comment by eemurphy** [comment]
closing and creating new PR from a healthy branch

**Comment by JakobGray** [comment]
For future record, you don't have to open a new PR when you rebase. You can just force push to your own branch.

**Pull request closed without merging**
