### PR TITLE
update CRDs to use v0.16.1 controller-gen (https://issues.redhat.com/browse/ACM-13685)

### PR DESCRIPTION
**Pull request by birsanv**
# Description

Update CRDs using v0.16.1 controller-gen version

## Related Issue

https://issues.redhat.com/browse/ACM-13685

## Changes Made

Provide a clear and concise overview of the changes made in this pull request.

## Screenshots (if applicable)

Add screenshots or GIFs that demonstrate the changes visually, if relevant.

## Checklist

- [x] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [x] I have added/updated relevant unit tests (if applicable).
- [x] I have ensured that my code follows the project's coding standards.
- [x] I have checked for any potential security issues and addressed them.
- [x] I have added necessary comments to the code, especially in complex or unclear sections.
- [x] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

Add any additional notes, context, or information that might be helpful for reviewers.

## Reviewers

Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 @reviewer2`

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

### CODE REVIEW

**Comment by birsanv** [comment]
/cc @dislbenn 
@dislbenn I am not sure why the RBAC validation fails here https://github.com/stolostron/multiclusterhub-operator/actions/runs/10616963835/job/29428633661?pr=1695#step:9:14

I see another PR updating the addondeploymentconfigs  role but that one didn't get in due to a sonar code coverage error https://github.com/stolostron/multiclusterhub-operator/pull/1690

**Comment by dislbenn** [comment]
@birsanv most likely you'll need to pull the latest changes and the run `go generate` and `make manifests`. That should help to resolve your issue.

**Pull request merged**
