### PR TITLE
Type added for MCE sub/csv status in MCH spec

### PR DESCRIPTION
**Pull request by eemurphy**
Issue: https://github.com/stolostron/backlog/issues/20377 

Signed-off-by: Erin Murphy <erinmurp@redhat.com>

### CODE REVIEW

**Review by zkayyali812 — APPROVED** [review]

**Comment by JakobGray** [comment]
What does the "unhappy case" look like here? Does the subscription always display Available? For the csv does the Type only get set when `phase == "Succeeded" && reason == "InstallSucceeded"`?

**Review by JakobGray — COMMENTED** [review]
What does the "unhappy case" look like here? Does the subscription always display Available? For the csv does the Type only get set when phase == "Succeeded" && reason == "InstallSucceeded"?

**Comment by eemurphy** [comment]
@JakobGray For sub it only returns an unknown status or an available status, there seems no other option. For csv you're right though, I see I can make a change to that so it gets its Type the same way mapMultiClusterEngine method does and that should cover an "unhappy" case. I will create a new PR with that change

**Pull request closed without merging**
