### PR TITLE
report errors for resources we are not handling in the script

### PR DESCRIPTION
**Pull request by kurwang**

### CODE REVIEW

**Comment by kurwang** [comment]
Added logic to handle adding configmap resource

**Review by JakobGray — APPROVED** [review]
Tested on a fork and it failed successfully 👍  

```
INFO:root:Check to see if there are resources in the csv that aren't getting picked up
INFO:root:Copying over other resources in the bundle if they exist ...
INFO:root:From directory '/Users/jdgray/github/multiclusterhub-operator/hack/bundle-automation/tmp/search-v2-operator/bundle/manifests'
ERROR:root:Found a file of a resource that is not being handled called 'ValidatingWebhookConfiguration' in '/Users/jdgray/github/multiclusterhub-operator/hack/bundle-automation/tmp/search-v2-operator/bundle/manifests
ERROR:root:Found a resource in either the manifest or csv we aren't handling
➜  multiclusterhub-operator git:(bundlereports) ✗ echo $?                                                                          
1
```

**Comment by kurwang** [comment]
Hey Jake can the do not merge label be removed or are we waiting on something

**Comment by JakobGray** [comment]
It can come off. I just didn't want to unintentionally merge it before you were ready by approving it.

**Pull request merged**
