### PR TITLE
Add `acm-cli` console CLI download

### PR DESCRIPTION
**Pull request by dhaiducek**
# Description

Add an `acm-cli` chart to add a plugin to download CLIs from the OCP console.

## Related Issue

https://issues.redhat.com/browse/ACM-12551

## Changes Made

Adds a new chart with Deployment, Route, Service, and ConsoleCLIDownload manifests to deploy the `acm-cli` image. The image is a Golang HTTP server that serves the files made available in the console via the ConsoleCLIDownload plugin.

## Screenshots (if applicable)

image

## Checklist

- [ ] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [ ] I have added/updated relevant unit tests (if applicable).
- [ ] I have ensured that my code follows the project's coding standards.
- [ ] I have checked for any potential security issues and addressed them.
- [ ] I have added necessary comments to the code, especially in complex or unclear sections.
- [ ] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

--

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

### CODE REVIEW

**Comment by dislbenn** [comment]
@dhaiducek for the sonarcloud code analysis, we will most likely have to override since it will complain about storage not being defined in the manifests yaml. This is something we are planning to address in the upcoming release.

**Comment by dhaiducek** [comment]
There's a skew in Prow because `ENVTEST_K8S_VERSION` is hard-coded there. I've updated it, which should get the CI here to pass:
- https://github.com/openshift/release/pull/57170

**Comment by dhaiducek** [comment]
Also, based on your comments, I took the liberty of pressing "Accept" on the SonarCloud emphemeral issue storage issue since you're aware of it an it's considered tech debt in this PR.

**Pull request merged**
