### PR TITLE
Fix policy template unknown API issue when ManagedServiceAccount is not enabled

### PR DESCRIPTION
**Pull request by sahare**
# Description

When ManagedServiceAccount feature is not enabled on MultiClusterEngine, the policy template encounters error calling lookup: one or more API resources are not installed on the API server.

## Related Issue

https://issues.redhat.com/browse/ACM-10214

## Changes Made

Before looping through ManagedServiceAccount instances, get the MultiClusterEngine cluster scoped instance and check whether managedserviceaccount component is enabled

## Screenshots (if applicable)

Add screenshots or GIFs that demonstrate the changes visually, if relevant.

## Checklist

- [x] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [ ] I have added/updated relevant unit tests (if applicable).
- [x] I have ensured that my code follows the project's coding standards.
- [x] I have checked for any potential security issues and addressed them.
- [ ] I have added necessary comments to the code, especially in complex or unclear sections.
- [x] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

Add any additional notes, context, or information that might be helpful for reviewers.

## Reviewers

Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 @reviewer2`

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

### CODE REVIEW

**Review by birsanv — APPROVED** [review]
lgtm

**Comment by dislbenn** [comment]
@sahare is the fix set for 2.10? Our current repo is set for 2.11 code changes? If so, you will need to cherry pick this PR.

**Comment by sahare** [comment]
@dislbenn Yes the fix needs to be merged in 2.10, I added the cherry-pick comment. Thanks!

**Pull request merged**
