### PR TITLE
remove hub-crds references

### PR DESCRIPTION
**Pull request by ray-harris**
Signed-off-by: Ray Harris <raharris@redhat.com>

### CODE REVIEW

**Review by JakobGray — COMMENTED** [review]
Given the dockerfile changes this will likely have implications in the midstream/downstream as well

**Comment by ray-harris** [comment]
Midstream PR:
https://gitlab.cee.redhat.com/acm-cpaas-midstream/multiclusterhub-operator/-/merge_requests/97

**Comment by ray-harris** [comment]
@JakobGray The midstream PR is failing. Talked with Brian Smith and the upstream has to be merged first.

**Pull request merged**
