### PR TITLE
Update MCE community channel to match current engine version

### PR DESCRIPTION
**Pull request by vkareh**
# Description

This PR fixes a typo in the community channel for MCE

## Related Issue

If applicable, please reference the issue(s) that this pull request addresses.

## Changes Made

Updated MCE community channel version to correct version for stolostron

## Screenshots (if applicable)

Add screenshots or GIFs that demonstrate the changes visually, if relevant.

## Checklist

- [ ] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [ ] I have added/updated relevant unit tests (if applicable).
- [ ] I have ensured that my code follows the project's coding standards.
- [ ] I have checked for any potential security issues and addressed them.
- [ ] I have added necessary comments to the code, especially in complex or unclear sections.
- [ ] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

Add any additional notes, context, or information that might be helpful for reviewers.

## Reviewers

Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 @reviewer2`

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

### CODE REVIEW

**Comment by dislbenn** [comment]
@vkareh I believe the community version for ACM 2.12 / MCE 2.7 is `0.5`.

**Comment by vkareh** [comment]
@dislbenn - thanks for the reply. I'm using OKD and installing stolostron directly from OperatorHub. The community version provided there is 0.3 and 0.4, but the 0.4 fails because it expects stolostron-engine to be 0.5:
```
2024-08-01T14:29:41.998Z	INFO	reconcile	Failed to find a suitable catalogsource.	{"error": "no stolostron-engine packageManifests found with desired channel community-0.5"}
```
I managed to fix it locally by updating the annotation of the MCH to force 0.4 and it fixed the issue. Also had to add the `DISABLE_MCE_MIN_VERSION` env var to the csv.

**Review by dislbenn — APPROVED** [review]

**Pull request merged**
