### PR TITLE
helmrepo and appsub content removal

### PR DESCRIPTION
**Pull request by eemurphy**
Signed-off-by: Erin Murphy <erinmurp@redhat.com>

issue: https://github.com/stolostron/backlog/issues/26604

### CODE REVIEW

**Comment by JakobGray** [comment]
@eemurphy Does this PR address the criteria
- helmrepo, channel, and subscription packages removed in multiclusterhub-operator
- Resources are cleaned up after an upgrade to 2.7

**Comment by eemurphy** [comment]
> @eemurphy Does this PR address the criteria
> 
> * helmrepo, channel, and subscription packages removed in multiclusterhub-operator
> * Resources are cleaned up after an upgrade to 2.7

Just to make sure I understand - I did not actually remove the packages, but I left them since they were used to clean up resources sometimes. Should I instead delete everything under pkg/helmrepo, pkg/channel, and pkg/subscription, and then separately write some code to make sure that they are all cleaned up on upgrade?

**Comment by JakobGray** [comment]
Yes. The objective of the issue is to completely offboard the helm-repo because we are no longer using it with the completion of the management-ingress removal. When you were testing was the helm-repo component still being installed on the cluster?

**Comment by eemurphy** [comment]
@JakobGray No I did not see it installed, but I am second guessing if it was fully uninstalled on an update though. I'm actually removing all of those packages now, I think I have a good idea of how to clean up on upgrade too.

**Comment by eemurphy** [comment]
Note - commit [b569695](https://github.com/stolostron/multiclusterhub-operator/pull/930/commits/b5696951d281e8794032eef97a19450507d08c8d) removes helm-repo but does not clean up on upgrade. Still working on that part, will try and commit it tonight as well

**Comment by JakobGray** [comment]
@cameronmwall Can you review the PR as it is thus far? (Keeping in mind some updates are coming for upgrade)

**Comment by JakobGray** [comment]
@eemurphy  Have you tested the cleanup on upgrade part?

**Comment by cameronmwall** [comment]
a couple of things that I noticed when testing: repo is still in the list of all components so it is allowed by the web look to be passed in the list. Not sure if we want to take that off
also, I'm not sure why this would be or if I missed an existing issue, but when I deleted the mch, the volsync-controller deployment was left behind

**Comment by JakobGray** [comment]
Thanks Cameron. We actually do want the repo to be allowed by the webhook because otherwise users with the helmrepo in their config (either from an upgrade or explicit configuration) will encounter breakage. The safer path is to allow it, but then prune it out. I'm not sure what the deal is with volsync. It sounds like it would be unrelated to this change, but worth checking.

**Comment by eemurphy** [comment]
@JakobGray @cameronmwall I just tested and got that same volsync thing, I'm looking into what's causing that now but I think it's unrelated

**Comment by JakobGray** [comment]
I made some updates to include cleanup of the helm-repo Deployment and Service and the charts-v1 Channel on upgrade. I tested this by installing with the existing image and checking that the resources are present, then updating to my image and confirming that they are cleaned up with these commands: 

``` 
oc get channel charts-v1 -n open-cluster-management
oc get deployment multiclusterhub-repo -n open-cluster-management
oc get service multiclusterhub-repo -n open-cluster-management
```

The volsync deployment seems to be leaking because it wasn't added to the finalizer code so I've made that change. I also removed the go module dependencies since we are no longer using them.

**Pull request merged**
