### PR TITLE
Fix ingress logic

### PR DESCRIPTION
**Pull request by dhaiducek**
# Description

The ingress value is currently being overridden even when it's discovered successfully.

## Related Issue

Slack thread: https://redhat-internal.slack.com/archives/CUEMEHRA9/p1727470385708379

## Changes Made

Removes the `r.CacheSpec.IngressDomain` check so that the Ingress is properly checked and the env set accordingly. 

## Screenshots (if applicable)

-

## Checklist

- [ ] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [ ] I have added/updated relevant unit tests (if applicable).
- [ ] I have ensured that my code follows the project's coding standards.
- [ ] I have checked for any potential security issues and addressed them.
- [ ] I have added necessary comments to the code, especially in complex or unclear sections.
- [ ] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

I wondered whether the original goal was to _not_ re-fetch the ingress and have a conditional at the top, but since (I think?) the client caches the ingress, the re-fetch ought to be fairly cheap in case for whatever reason the ingress value changes.

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

### CODE REVIEW

**Comment by dhaiducek** [comment]
Not sure if this is correct, but, in addition to the update to the ingress logic, I added `make manifests` to the "regenerate bundles" workflow. At this point I've had to run it a couple times after the workflow ran, so it seems like it should be baked into the PRs? (Not sure what magic happens where it's not already blocking...)

I added a Dependabot configuration that we in GRC use to keep the GitHub Action versions up-to-date.

Finally, I swapped out the `controller-gen` command in the rbac workflow for `make manifests` since they're equivalent.

If any of these isn't desirable or should be in a separate PR, let me know and I can make the adjustment!

**Review by dislbenn — COMMENTED** [review]
/lgtm
/unhold

**Comment by dhaiducek** [comment]
@dislbenn I went ahead and addressed the SonarCloud coverage issue by deploying the Ingress to the testenv, so this PR should now have all its CI passing in a moment to be re-reviewed.

While running the `unit-tests` target, I also noticed that the tests are reaching out to my currently configured cluster, which should probably be addressed in the future (that one looks like it might be a fair bit more work, and this PR already has quite a bit of scope creep! 😅 )

**Comment by dislbenn** [comment]
@

> @dislbenn I went ahead and addressed the SonarCloud coverage issue by deploying the Ingress to the testenv, so this PR should now have all its CI passing in a moment to be re-reviewed.
> 
> While running the `unit-tests` target, I also noticed that the tests are reaching out to my currently configured cluster, which should probably be addressed in the future (that one looks like it might be a fair bit more work, and this PR already has quite a bit of scope creep! 😅 )

We have a task for us to address the `unit-tests` target. That was something that surprised the team as well, so I'm guessing that was left over from some legacy testing.

**Pull request merged**
