### PR TITLE
Auto-select MCE catalogsource based on latest available version

### PR DESCRIPTION
**Pull request by JakobGray**
Issue: https://issues.redhat.com/browse/ACM-3331

In addition to determining which catalogsource to use for MCE based on available channel, select the catalogsource with the latest available version within that channel.

### CODE REVIEW

**Comment by eemurphy** [comment]
This is for the main branch which connects to 2.8 now, we need this in the 2.7 branch instead, correct?

**Comment by JakobGray** [comment]
> This is for the main branch which connects to 2.8 now, we need this in the 2.7 branch instead, correct?

Changes should be merged into the current dev branch first and then cherrypicked into previous release branches

**Pull request merged**
